app:
  build: .
  command: sh docker/deploy.sh
  volumes:
    - .:/usr/src/app
    - bundle:/usr/local/bundle
    - assets:/usr/src/app/public/assets
    - ./public/uploads:/usr/src/app/public/uploads
    - logs:/usr/src/app/log
    - tmp:/usr/src/app/tmp
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
  links:
    - db
  restart: always
  expose:
    - "3000"
db:
  image: postgres

nginx:
  image: nginx
  links:
    - app
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./public:/usr/share/nginx/html
    - ./public/uploads:/usr/share/nginx/html/uploads
    - assets:/usr/share/nginx/html/assets
    - logs:/var/log/nginx
  ports:
    - "3000:80"
  restart: always
